src/Client/Logger.ts, src/events/guildScheduledEventDelete.ts, src/events/ready.ts, src/interactions/modals/event-create.ts, src/interactions/select_menus/vc.ts, src/structures/Constants.ts, src/util/event/event-select-menus.ts, src/util/event/index.ts
=> Fix Event permission management

src/interactions/modals/event-create.ts, src/interactions/select_menus/vc.ts, src/structures/Constants.ts
=> Handle event permissions better

.env.sample, src/Client/Logger.ts, src/events/ready.ts, src/structures/Constants.ts, src/structures/sme.ts
=> Fix startup configuration

src/events/messageCreate.ts, src/events/messageReactionAdd.ts, src/events/ready.ts, src/features/amplify/index.ts, src/util/Database/Schema/timedRoles.ts, src/util/Database/index.ts, src/util/amplify/index.ts, src/util/state/state.ts
- added DB checks
- prevents bot recantations from counting
=> Amplify Update

assets/guide.json, locales/en-US/admin.ftl, src/commands/chat/builders/admin.ts, src/commands/chat/execution/admin/index.ts, src/commands/chat/execution/admin/rules.ts, src/events/interactionCreate.ts
generates rules channel posts and implements buttons to flip through the sections of the rules
currently only supports english as I do not want to make a non json file for this right now
=> Rules command

src/structures/helpers.ts
Updates backend URLs to match the changes in https://github.com/Progressive-Victory/crm-backend/pull/79
=> Update backend endpoints

.gitignore, assets/guide.json, locales/en-US/admin.ftl, locales/en-US/lead.ftl, src/commands/chat/builders/admin.ts, src/commands/chat/builders/lead.ts, src/commands/chat/execution/admin/index.ts, src/commands/chat/execution/admin/rules.ts, src/commands/chat/execution/lead/ping.ts, src/events/interactionCreate.ts, src/index.ts, src/structures/helpers.ts
Update production branch with the recent changes:
* new backend endpoints
* fixed state lead ping command
* added /rules feature to put out a button based directory of rules. Admin only, not necessarily to be used yet
=> Update production branch with recent fixes

.github/workflows/main.yml, .github/workflows/prod.yml
In the production environment, yarn is not being resolved properly, so this should hopefully address that
=> Fix yarn path not being resolved on deployment

.github/workflows/main.yml, .github/workflows/prod.yml, .gitignore, assets/guide.json, locales/en-US/admin.ftl, locales/en-US/lead.ftl, src/commands/chat/builders/admin.ts, src/commands/chat/builders/lead.ts, src/commands/chat/execution/admin/index.ts, src/commands/chat/execution/admin/rules.ts, src/commands/chat/execution/lead/ping.ts, src/events/interactionCreate.ts, src/index.ts, src/structures/helpers.ts
=> Address deployment resolving yarn

.github/workflows/main.yml, .github/workflows/prod.yml, .vscode/settings.json
The unrelated change is a vscode update that keeps getting forced on me, might as well incorporate it here.
The fix addresses the fact that yarn is installed with nvm, so this should address deployment issues, ideally.
=> initialize nvm in github action

src/events/guildScheduledEventCreate.ts, src/events/messageReactionAdd.ts, src/interactions/modals/event-create.ts, src/util/amplify/index.ts, src/util/database/schema/events.ts
=> Improve partials handling for event creation

src/index.ts
Temporarily remove all partials for now since I can't figure out where the error coming from the database with creation + missing guildID. This shouldn't break any functionality in particular.
=> temporarily remove partials for now

src/index.ts, src/util/database/schema/events.ts
last resort attempt, ideally we don't keep this code around
=> capture uncaught exceptions to prevent crashes

.vscode/extensions.json, .vscode/settings.json, eslint.config.js, package.json, src/index.ts, yarn.lock
Update ESLint to use latest package and flat package config
=> eslint bump

src/Classes/Interaction.ts, src/Classes/index.ts, src/index.ts, src/interactions/select_menus/index.ts, src/interactions/select_menus/move.ts
Dorp down for the move command was missing.
=> missing move dropdown

src/commands/chat/state-admin.ts, src/commands/chat/state.ts, src/commands/index.ts, src/models/Setting.ts, src/models/State.ts, src/models/Warn.ts, src/models/WarnSearch.ts, src/util/states/types.ts
adding state configurations command
=> add settings for config state settings

package.json, src/commands/chat/state.ts, src/features/state/index.ts, src/features/state/ping.ts, src/features/state/types.ts, src/index.ts, src/interactions/buttons/warn.ts, src/interactions/modals/index.ts, src/interactions/modals/statePing.ts, yarn.lock
- Update state embed to [components v2](https://discord.com/developers/docs/components/overview)
- added message and title options to command and modal
=> enhanced state ping

package.json, src/commands/chat/state.ts, src/features/state/index.ts, src/features/state/ping.ts, src/features/state/types.ts, src/index.ts, src/interactions/buttons/warn.ts, src/interactions/modals/statePing.ts, yarn.lock
* Add voice channel update event (#148)
* Add voice channel update event
* Fix other spelling mistake
* deduplicate code
* reduce repeated code
* update settings
* type protection added
* added comment
* changes for ben
* added stage event
* ben formatting changes
* fix: make lint run on dev
---------
* add settings for config state settings (#149)
* add settings for config state settings
* update naming
* Update State Ping Command (#151)
* add settings for config state settings
* update naming
* updated state ping
* enhanced state ping
* bumb discord.js
---------
=> Enhanced state ping (#154)

package.json, src/events/client/debug.ts, src/interactions/modals/statePing.ts, yarn.lock
- when creating state ping using modal message are sent to state channel
=> Fix modal sending to the wrong channel

src/commands/chat/setting.ts, src/events/README.md, src/events/guild_member/guildMemberUpdate.ts, src/models/Setting.ts
This tries to close #161
- setting.ts added field for log files
- events/README.md updated link to point to correct page
- guildMemberUpdate.ts added logic at the end of the event handler
- setting.ts added command registration for setting log channel for this feature
=> Add Nickname logging

src/commands/chat/mute.ts, src/commands/index.ts
it sets mute, will log the mute, will send a message to the muted user, and if the user and muter are in the same voice channel it will send a message in the chat too.
user direct message
server log
voice chat message
=> Add mute command

README.md, src/commands/chat/README.md, src/commands/context_menu/README.md, src/events/README.md, src/interactions/buttons/README.md, src/interactions/modals/README.md, src/interactions/select_menus/README.md
* Fix formatting to mostly comply with markdownlint
* Fix incorrect links to documentation
* Add relative links to project files where relevant
* Add high-level overview section with references to relevant GCP and discord.js documentation
- Why is this feature needed?
- The existing READMEs don't play nicely with markdownlint, have dead links, etc.
- Does this affect another system?
- No changes to functionality, only documentation
- Is this related to an exsiting [Issue]
- No existing issue
=> Update existing READMEs

package.json, pnpm-lock.yaml, src/events/guild_member/guildMemberVoiceUpdate.ts, src/events/guild_scheduled_event/guildScheduledEventUpdate.ts
Updated deps and removed superfluous error logging. Hopefully this will address the event crashing issue.
=> Bugfix/   /diagnostics added to mark attendance

src/commands/chat/state-admin.ts, src/commands/chat/state.ts, src/events/guild_member/guildMemberVoiceUpdate.ts, src/events/guild_scheduled_event/guildScheduledEventUpdate.ts, src/features/state/ping.ts, src/interactions/modals/statePing.ts
updated the ping command you support announcement channels.
fixed bug if DB repose is late causing command to error
fixed bug when updating states causing crashes
=> Ping update
